version: '3.1'

services:
  flask-ecs:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - AWS_ACCESS_KEY_ID="AKIAXQUI6OPLC52OYHKS"
        - AWS_SECRET_ACCESS_KEY="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"
        - AWS_DEFAULT_REGION="ap-south-1"
    container_name: flask-ecs
    ports:
      - 5000:5000
    # bridge - connect to docker container from localhost
    network_mode: bridge