version: '3.1'

services:
  flask-ecs:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
    container_name: flask-ecs
    ports:
      - 5000:5000
    # bridge - connect to docker container from localhost
    network_mode: bridge